name: eShopOnWeb Build and Test

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
        include-prerelease: true

    - name: Build with dotnet
      run: dotnet build ./eShopOnWeb.sln --configuration Release
    
    # Separate publish step for the Web project
    - name: dotnet publish Web
      run: dotnet publish ./src/Web/Web.csproj -c Release -o "${{env.DOTNET_ROOT}}/myapp/Web"

    # Separate publish step for the PublicApi project
    - name: dotnet publish PublicApi
      run: dotnet publish ./src/PublicApi/PublicApi.csproj -c Release -o "${{env.DOTNET_ROOT}}/myapp/PublicApi"

    # Upload the Web artifact
    - name: Upload Web artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
          name: eShopOnWeb-Web
          path: ${{env.DOTNET_ROOT}}/myapp/Web
          
    # Upload the PublicApi artifact
    - name: Upload PublicApi artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
          name: eShopOnWeb-PublicApi
          path: ${{env.DOTNET_ROOT}}/myapp/PublicApi
